### ISSUE TITLE
Logo Color

### ISSUE THREAD

**Issue by ixkaito** [bargees/barge-logo#1]
@ailispaw What color do you prefer?

**Comment by ailispaw** [comment]
Hmm. I have no idea...

**Comment by ailispaw** [comment]
BTW, the letters are embossed?

**Comment by ailispaw** [comment]
Single color? Or multiple colors like containers?

**Comment by ailispaw** [comment]
Two tones for upper and lower?

**Comment by ixkaito** [comment]
> BTW, the letters are embossed?

No. If you mean transparent, yes.

> Single color? Or multiple colors like containers?

I imagined single color. Here are some examples:

![barge-logo-colors](https://cloud.githubusercontent.com/assets/5457539/18183568/eda2ddbe-70cf-11e6-9409-f4b3203a5afd.png)

**Comment by ailispaw** [comment]
I see. Thanks.

I may choose blue, but it would be darker or different flavor of blue.
The black one is still good as well.

**Comment by ailispaw** [comment]
http://www.colordic.org/w/
It could be 紺碧, 瑠璃色, 瑠璃紺, 紺瑠璃, 藍色, 紺色, 紺青 or 濃藍.

**Comment by ixkaito** [comment]
I added the 紺碧 one. 00de7fa

![barge-logo](https://cloud.githubusercontent.com/assets/5457539/18214251/f00e11ce-7186-11e6-8d64-d208f30eb3b5.png)

**Comment by ailispaw** [comment]
@ixkaito Thank you so much. That looks nice.
Do you recommend that color?

**Comment by ixkaito** [comment]
@ailispaw Yes, I love it.

**Comment by ailispaw** [comment]
OK. I see.
Could you make some more samples for me?
瑠璃色, 瑠璃紺, 紺瑠璃, 紺青

**Comment by ailispaw** [comment]
I love it, too, but I would like to compare with others.

**Comment by ixkaito** [comment]
@ailispaw Here you are.

![barge-logos](https://cloud.githubusercontent.com/assets/5457539/18222519/e91152c0-71d4-11e6-8e96-e54fcfe1296f.png)

**Comment by ailispaw** [comment]
@ixkaito Thank you soooo much!!
Let me think for a while.

**Comment by ailispaw** [comment]
I haven't decided yet, but it would be 紺碧, 瑠璃色 or between them.
I realize that color depends on display and lights, and it's hard to decide. :(

**Comment by ailispaw** [comment]
On second thought, I have mostly decided on 紺瑠璃.

BTW, although it may be caused by PNG or my display, increasing its contrast a bit looks better and clear for me.

**Comment by ixkaito** [comment]
> On second thought, I have mostly decided on 紺瑠璃.

OK!

> BTW, although it may be caused by PNG or my display, increasing its contrast a bit looks better and clear for me.

It would look very similar to 瑠璃紺.

![barge-logo](https://cloud.githubusercontent.com/assets/5457539/18236242/125648c6-735f-11e6-86d9-d948a9520ae6.png)

**Comment by ailispaw** [comment]
Yeah. Hmm. I guess it's too high and bright.
I see some jaggy on the edge.

It's not so different from the original but just a little bit to make letters clear.

**Comment by ailispaw** [comment]
Or the original one is just fine.

**Comment by ailispaw** [comment]
It may look same.

![colors](https://cloud.githubusercontent.com/assets/10327896/18237336/d7779342-72e4-11e6-9ef2-21c22a6284ec.png)

**Comment by ixkaito** [comment]
Here are some contrast tests.

\+ 20
![barge-logo-20](https://cloud.githubusercontent.com/assets/5457539/18293164/16c14da2-74cc-11e6-928b-3512e52b968d.png)

\+ 30
![barge-logo-30](https://cloud.githubusercontent.com/assets/5457539/18293163/16bec730-74cc-11e6-9895-9c35f307d120.png)

\+ 40
![barge-logo-40](https://cloud.githubusercontent.com/assets/5457539/18293162/16be6d58-74cc-11e6-8129-059d47bad4a7.png)

> I see some jaggy on the edge.

Please don't worry. It's just a test.

**Comment by ailispaw** [comment]
Thanks. They are much brighter than what I imagined. I might have done with less than +5, I guess.
Let's go for the original 紺瑠璃.
Thank you so much for taking your time.

**Comment by ixkaito** [comment]
Never mind. I'll push 紺瑠璃 :)
