### ISSUE TITLE
Jaggies on the organization icon

### ISSUE THREAD

**Issue by ixkaito** [bargees/barge-logo#2]
@ailispaw I saw the icon of the organization has some jaggies. You can use this one for the organization icon.

![barge-icon](https://cloud.githubusercontent.com/assets/5457539/18368800/e9a76bb6-765c-11e6-8b5d-315eaf9f1e45.png)

**Comment by ailispaw** [comment]
@ixkaito Thanks a lot!!

**Comment by ailispaw** [comment]
Done.

**Comment by ixkaito** [comment]
Looks good!

**Comment by ailispaw** [comment]
@ixkaito 
I need a favicon and logo images for barge-os-com in the future.
May I ask you for that later?
https://github.com/bargees/barge-os.com

**Comment by ixkaito** [comment]
@ailispaw Of course!

**Comment by ailispaw** [comment]
Thank you so much!
